import React,{useEffect,useState} from 'react';
import {api} from '../api/client';
import {PageShell,SectionTitle} from '../components/Chrome';
import {DecisionBadge,RiskBadge} from '../components/Cards';
import {FlaskConical,ShieldOff,ShieldCheck,Play,Skull,CheckCircle2,ArrowRight,Timer,Target,BarChart3,Database,GitCompare,Braces} from 'lucide-react';
export default function AttackLab(){
 const [scenarios,setScenarios]=useState<any[]>([]),[sid,setSid]=useState('attack_env'),[res,setRes]=useState<any>(null),[loading,setLoading]=useState(false),[bench,setBench]=useState<any[]>([]),[metrics,setMetrics]=useState<any>(null),[manifest,setManifest]=useState<any>(null),[compiler,setCompiler]=useState<any[]>([]);
 useEffect(()=>{Promise.all([api.get('/api/v1/attack-lab/scenarios'),api.get('/api/v1/experiments/compare'),api.get('/api/v1/research/manifest'),api.post('/api/v1/research/compiler-ablation',{split:'test',persist:false})]).then(([x,c,m,p])=>{setScenarios(x);if(x[0])setSid(x[0].id);setBench(c.series||[]);setManifest(m);setCompiler(p.series||[])})},[]);
 async function run(){setLoading(true);try{setRes(await api.post('/api/v1/attack-lab/compare',{scenario_id:sid}));setMetrics(await api.post('/api/v1/benchmarks/bench_v30/evaluate',{mode:'trajectory_full',split:'test'}))}finally{setLoading(false)}}
 const cur=scenarios.find(x=>x.id===sid);
 return <PageShell title="攻击实验室"><SectionTitle eyebrow="RED TEAM / AGENTGUARD-BENCH V3" title="用冻结测试集证明安全能力，而不是只做一段演示动画" desc="V3 将 100 条 GT Candidate、Runtime 消融与 P2C-V 编译消融统一到可重复实验链。" action={<button className="btn primary" onClick={run} disabled={loading}><Play size={15}/>{loading?'正在运行实验':'运行攻击 + Frozen Test'}</button>}/>
  <div className="research-manifest"><div><Database size={18}/><span>GT Candidate</span><b>{manifest?.scenario_count||'—'} scenarios</b></div><div><Target size={18}/><span>Frozen Test</span><b>{manifest?.splits?.test||'—'} cases</b></div><div><Braces size={18}/><span>Policy GT Candidate</span><b>{manifest?.policy_ground_truth_count||'—'} rules</b></div><div><GitCompare size={18}/><span>Threat Types</span><b>{manifest?Object.keys(manifest.categories||{}).length:'—'} categories</b></div></div>
  <div className="attack-layout-v2"><section className="panel attack-menu"><div className="panel-head"><span><FlaskConical size={16}/>现场攻击场景</span><span className="chip danger">CONTROLLED</span></div>{scenarios.map(s=><button key={s.id} onClick={()=>{setSid(s.id);setRes(null)}} className={sid===s.id?'selected':''}><div className="attack-icon"><Target size={18}/></div><div><b>{s.name}</b><small>{s.type}</small><p>{s.description}</p></div><RiskBadge value={s.level.toUpperCase()}/></button>)}</section>
   <section className="panel attack-stage"><div className="attack-intro"><small>SELECTED ATTACK</small><h3>{cur?.name||'选择攻击场景'}</h3><p>{cur?.description}</p></div><div className="compare-grid"><div className="compare-card off"><div className="compare-head"><ShieldOff size={22}/><div><small>CONTROL GROUP</small><b>AgentGuard OFF</b></div></div>{res?<><div className="attack-result bad"><Skull size={31}/><strong>攻击成功</strong><span>危险动作抵达 Tool</span></div><DecisionBadge value={res.off.decision}/><p>{res.off.reason}</p><div className="latency"><Timer size={14}/>{res.off.latency_ms} ms</div></>:<div className="attack-placeholder">等待运行实验</div>}</div><div className="compare-divider"><ArrowRight size={22}/><span>VS</span></div><div className="compare-card on"><div className="compare-head"><ShieldCheck size={22}/><div><small>AGENTGUARD FULL</small><b>AgentGuard ON</b></div></div>{res?<><div className="attack-result good"><CheckCircle2 size={31}/><strong>安全边界保持</strong><span>危险路径未进入真实工具层</span></div><DecisionBadge value={res.on.decision}/><p>{res.on.reason}</p><div className="latency"><Timer size={14}/>{res.on.latency_ms} ms</div></>:<div className="attack-placeholder">等待运行实验</div>}</div></div></section>
  </div>
  <div className="two-col wide-left"><section className="panel"><SectionTitle eyebrow="RUNTIME ABLATION / FROZEN TEST" title="轨迹感知到底有没有价值" desc="测试集固定后比较 No Guard、Single-Step 与 Full Trajectory；跨步骤攻击不会给单步防护“送答案”。"/><div className="benchmark-table"><div className="bench-head"><span>模式</span><span>ASR ↓</span><span>Fidelity ↑</span><span>FPR ↓</span><span>Latency</span></div>{bench.map((x:any)=><div key={x.name}><b>{x.name}</b><span className={x.asr<.2?'good-num':'bad-num'}>{(x.asr*100).toFixed(0)}%</span><span>{(x.policy_fidelity*100).toFixed(0)}%</span><span>{(x.fpr*100).toFixed(0)}%</span><span>{x.latency_ms} ms</span></div>)}</div></section><section className="panel"><SectionTitle eyebrow="BENCHMARK RUN" title="AgentGuard-Bench V3 Test"/>{metrics?<div className="bench-summary"><BarChart3 size={30}/><strong>{metrics.summary?.passed}/{metrics.summary?.total}</strong><span>Frozen test decisions matched GT Candidate</span><div><small>Attack Success</small><b>{(metrics.metrics.attack_success_rate*100).toFixed(0)}%</b></div><div><small>False Positive</small><b>{(metrics.metrics.false_positive_rate*100).toFixed(0)}%</b></div><div><small>Policy Fidelity</small><b>{(metrics.metrics.policy_fidelity*100).toFixed(0)}%</b></div></div>:<div className="attack-placeholder tall">运行一次实验后由后端真实计算 Test Split 指标</div>}</section></div>
  <section className="panel compiler-ablation"><SectionTitle eyebrow="P2C-V ABLATION / POLICY GROUND TRUTH" title="编译链消融：每一层到底增加了什么" desc="50 条 Policy GT Candidate Candidate 固定拆分；这里展示的是后端逐条比对计算的结果。"/><div className="compiler-ablation-grid">{compiler.map((x:any)=><div key={x.name}><small>{x.name.replaceAll('_',' ').toUpperCase()}</small><strong>{Math.round(x.semantic_accuracy*100)}%</strong><span>Semantic Accuracy</span><div className="mini-proof-row"><em>Graph {Math.round(x.graph_validity*100)}%</em><em>Formal {Math.round(x.formal_pass_rate*100)}%</em><em>Recall {Math.round(x.critical_rule_recall*100)}%</em></div></div>)}</div></section>
 </PageShell>
}
