import React,{useEffect,useRef,useState} from 'react';
import {api,wsBase} from '../api/client';
import {PageShell,SectionTitle} from '../components/Chrome';
import {DecisionBadge,RiskBadge} from '../components/Cards';
import {Bot,PlugZap,ShieldCheck,ArrowRight,Play,RotateCcw,FileKey2,Mail,ReceiptText,CheckCircle2,Clock3,Wrench,Radio,FileText,TerminalSquare} from 'lucide-react';
const scenarios:any={
 safe:{name:'安全文件读取',icon:FileText,payload:{agent_id:'agent_ops',tool_call:{tool_id:'mcp.files.read',action:'read',args:{}},resource_refs:['readme.txt'],declared_destination:'internal'}},
 env:{name:'Demo A · 敏感文件泄露',icon:FileKey2,payload:{agent_id:'agent_ops',tool_call:{tool_id:'mcp.files.read',action:'read',args:{}},resource_refs:['.env'],declared_destination:'internal'}},
 send:{name:'敏感数据外发',icon:Mail,payload:{agent_id:'agent_finance',tool_call:{tool_id:'mcp.email.send',action:'send',args:{to:'external@example.com',body:'customer summary'}},resource_refs:['customer_contact'],declared_destination:'external'}},
 refund:{name:'Demo B · 退款时序违规',icon:ReceiptText,payload:{agent_id:'agent_support',tool_call:{tool_id:'mcp.order.refund',action:'refund',args:{order_id:'ORD-1042',amount:980}},resource_refs:['order:ORD-1042'],declared_destination:'internal'}},
 amount:{name:'高金额审批',icon:ReceiptText,payload:{agent_id:'agent_finance',tool_call:{tool_id:'finance.transfer',action:'transfer',args:{amount:6800}},resource_refs:['finance:transfer'],declared_destination:'internal'}},
 cross:{name:'跨 Agent 敏感泄露',icon:Mail,payload:{agent_id:'agent_support',tool_call:{tool_id:'mcp.agent.message',action:'send',args:{}},resource_refs:['summary'],declared_destination:'agent:marketing'}},
 memory:{name:'Memory Poisoning',icon:FileKey2,payload:{agent_id:'agent_ops',tool_call:{tool_id:'mcp.task.run',action:'execute',args:{}},resource_refs:['task'],declared_destination:'internal'}},
};
export default function LiveRuntime(){
 const [key,setKey]=useState('safe'),[session,setSession]=useState<any>(null),[result,setResult]=useState<any>(null),[running,setRunning]=useState(false),[events,setEvents]=useState<any[]>([]),[recovery,setRecovery]=useState<any>(null),[recoveryRun,setRecoveryRun]=useState<any>(null),[retrying,setRetrying]=useState(false);const wsRef=useRef<WebSocket|null>(null);
 useEffect(()=>{const ws=new WebSocket(wsBase+'/ws/v1/runtime');ws.onmessage=e=>{try{const d=JSON.parse(e.data);if(d.type==='runtime.decision')setEvents(v=>[d,...v].slice(0,12))}catch{}};wsRef.current=ws;return()=>ws.close()},[])
 async function run(){setRunning(true);setResult(null);setRecovery(null);setRecoveryRun(null);try{const s=await api.post('/gateway/v1/sessions',{agent_id:scenarios[key].payload.agent_id});setSession(s);if(key==='cross'){await api.post('/gateway/v1/mcp/call',{session_id:s.session_id,trace_id:s.trace_id,agent_id:'agent_finance',tool_call:{tool_id:'mcp.files.read',action:'read',args:{}},resource_refs:['customer_contacts.csv'],declared_destination:'internal'})}if(key==='memory'){await api.post('/gateway/v1/mcp/call',{session_id:s.session_id,trace_id:s.trace_id,agent_id:'agent_ops',tool_call:{tool_id:'mcp.memory.seed',action:'memory_seed',args:{source:'untrusted-document'}},resource_refs:['memory'],declared_destination:'internal'})}const r=await api.post('/gateway/v1/mcp/call',{session_id:s.session_id,trace_id:s.trace_id,...scenarios[key].payload});setResult(r);if(r.recovery_id){setRecovery(await api.get(`/api/v1/recovery/${r.recovery_id}`))}}finally{setRunning(false)}}
 async function executeRecovery(){if(!recovery?.id)return;setRecoveryRun(await api.post(`/api/v1/recovery/${recovery.id}/execute`,{}))}
 async function retryOriginal(){if(!session||recoveryRun?.status!=='ready_to_retry')return;setRetrying(true);try{setResult(await api.post('/gateway/v1/mcp/call',{session_id:session.session_id,trace_id:session.trace_id,...scenarios[key].payload}));}finally{setRetrying(false)}}
 const decision=result?.decision||result?.gateway_decision; const executed=Boolean(result?.executed);
 const steps=[{name:'Agent',sub:scenarios[key].payload.agent_id,icon:Bot},{name:'Tool Call',sub:scenarios[key].payload.tool_call.tool_id,icon:PlugZap},{name:'AgentGuard',sub:'Context + Contract',icon:ShieldCheck},{name:'Decision',sub:decision||'WAITING',icon:decision==='REPAIR'?Wrench:decision==='ASK'?Clock3:CheckCircle2},{name:'Tool',sub:executed?'EXECUTED':'NOT REACHED',icon:TerminalSquare}];
 return <PageShell title="实时运行">
  <SectionTitle eyebrow="LIVE RUNTIME / MCP GATEWAY" title="Tool Call 进入真实工具前，先穿过 AgentGuard" desc="V3 的 MCP Call 会真的执行受控沙箱工具；DENY / ASK / REPAIR 时工具层不会收到危险调用。" action={<div className="live-state"><span className="pulse-dot"/>Runtime WebSocket</div>}/>
  <div className="runtime-layout-v2"><section className="panel scenario-panel"><div className="panel-head"><span>Competition Sandbox</span><span className="chip ok">REAL GATEWAY</span></div><div className="scenario-list">{Object.entries(scenarios).map(([k,v]:any)=>{const I=v.icon;return <button key={k} onClick={()=>{setKey(k);setResult(null);setRecovery(null);setRecoveryRun(null)}} className={key===k?'selected':''}><I size={18}/><span><b>{v.name}</b><small>{v.payload.tool_call.action} · {v.payload.resource_refs[0]}</small></span></button>})}</div><button className="btn primary full" onClick={run} disabled={running}><Play size={15}/>{running?'Gateway 判定中…':'执行 MCP Call'}</button><button className="btn ghost full" onClick={()=>{setResult(null);setRecovery(null);setRecoveryRun(null)}}><RotateCcw size={15}/>重置现场</button></section>
   <section className="panel runtime-stage-v2"><div className="runtime-path">{steps.map((s,i)=>{const I=s.icon;return <React.Fragment key={s.name}><div className={'runtime-step '+(i===2?'guard':'')+' '+(i===3&&decision?decision.toLowerCase():'')+' '+(i===4&&executed?'executed':'')}><div><I size={22}/></div><small>{s.name}</small><b>{s.sub}</b>{i===2&&<i/>}</div>{i<steps.length-1&&<div className={'runtime-link '+(result?'active':'')}><ArrowRight size={18}/><span/></div>}</React.Fragment>})}</div>{result?<div className={'decision-sheet-v2 '+String(decision||'').toLowerCase()}><div className="decision-top"><div><small>RUNTIME DECISION</small><DecisionBadge value={decision}/></div><RiskBadge value={result.risk_level}/></div><h3>{result.reason||'动作已通过安全验证并进入受控 Tool。'}</h3><div className="decision-meta"><span>trace <b>{result.trace_id}</b></span><span>latency <b>{result.latency_ms??'—'} ms</b></span><span>tool reached <b>{executed?'YES':'NO'}</b></span></div>{result.tool_result&&<pre className="tool-result">{JSON.stringify(result.tool_result,null,2)}</pre>}</div>:<div className="runtime-prompt"><Radio size={18}/><span>左侧选择一个场景。推荐先运行“安全文件读取”，再运行“.env 泄露”，现场差异最直观。</span></div>}</section>
  </div>
  <div className="two-col"><section className="panel"><SectionTitle eyebrow="SAFE RECOVERY" title="不只会拦截，还尝试继续完成任务" desc="Recovery Engine 生成最小修改路径，并重新验证原动作是否已满足安全条件。"/>{recovery?<><div className="recovery-steps">{recovery.safe_plan.map((s:any,i:number)=><div key={i}><span>{i+1}</span><div><b>{s.label}</b><small>{s.tool_id||s.action}</small></div>{i<recovery.safe_plan.length-1&&<i/>}</div>)}</div><button className="btn ghost full" onClick={executeRecovery} disabled={Boolean(recoveryRun)}>执行可自动恢复步骤</button>{recoveryRun&&<div className="recheck"><small>RECOVERY RECHECK</small><DecisionBadge value={recoveryRun.recheck?.decision}/><span>{recoveryRun.recheck?.reason}</span></div>}{recoveryRun?.status==='ready_to_retry'&&<button className="btn primary full" onClick={retryOriginal} disabled={retrying||Boolean(result?.executed)}><RotateCcw size={15}/>{retrying?'重新判定中…':'重新提交原操作'}</button>}</>:<div className="runtime-prompt slim">ALLOW 场景无需 Recovery；风险动作会在这里出现替代路径。</div>}</section>
   <section className="panel"><SectionTitle eyebrow="LIVE EVENT STREAM" title="Gateway 实时事件"/><div className="event-stream">{events.length?events.map((e:any,i)=><div key={i}><span className={'event-dot '+e.data.decision.toLowerCase()}/><div><b>{e.data.decision} · {e.data.risk_type}</b><small>{e.data.reason}</small></div><time>{String(e.timestamp).slice(11,19)}</time></div>):<div className="runtime-prompt slim">等待 Runtime Event…</div>}</div></section></div>
 </PageShell>
}
