import React,{useEffect,useState} from 'react';
import {api} from '../api/client';
import {PageShell,SectionTitle,Empty} from '../components/Chrome';
import {MetricCard,DecisionBadge,RiskBadge} from '../components/Cards';
import {ShieldCheck,Waypoints,ScanSearch,RotateCcw,Activity,ArrowRight,Braces,GitBranch,ShieldAlert,Database,Timer,Cpu,Network} from 'lucide-react';

export default function Overview(){
 const [ov,setOv]=useState<any>(null),[metrics,setMetrics]=useState<any>(null),[risks,setRisks]=useState<any[]>([]),[timeline,setTimeline]=useState<any[]>([]),[compare,setCompare]=useState<any[]>([]),[manifest,setManifest]=useState<any>(null);
 async function load(){const [a,b,c,d,e,m]=await Promise.all([api.get('/api/v1/dashboard/overview'),api.get('/api/v1/dashboard/metrics'),api.get('/api/v1/dashboard/risks'),api.get('/api/v1/dashboard/timeline'),api.get('/api/v1/experiments/compare'),api.get('/api/v1/research/manifest')]);setOv(a);setMetrics(b);setRisks(c);setTimeline(d);setCompare(e.series||[]);setManifest(m)}
 useEffect(()=>{load()},[]); const total=Object.values(ov?.decisions||{}).reduce((a:any,b:any)=>a+Number(b),0) as number;
 return <PageShell title="安全总览">
  <section className="hero-v2 hero-v3"><div className="hero-copy"><div className="hero-kicker"><span className="pulse-dot"/>AGENT RUNTIME SAFETY · V4.0 INTEGRATION BUILD</div><h2>在 Agent 触达真实世界之前，<em>先检查它的行为是否满足当前契约。</em></h2><p>Natural Policy → Typed Graph IR → Formal Verification → Trajectory Guard → Safe Recovery → Evidence Chain</p><div className="hero-tags"><span><Braces size={13}/>P2C-V V3</span><span><Cpu size={13}/>Model Checking</span><span><GitBranch size={13}/>Trajectory-aware</span><span><ShieldCheck size={13}/>Pre-execution Guard</span></div></div><div className="hero-orbit"><div className="orbit-ring r1"/><div className="orbit-ring r2"/><div className="orbit-core"><ShieldCheck size={31}/><b>BOUNDED</b><span>Sandbox + MCP Client</span></div><i className="orb o1"/><i className="orb o2"/><i className="orb o3"/></div></section>
  <div className="research-ribbon"><div><Database/><span>AgentGuard-Bench</span><b>{manifest?.scenario_count||'—'} GT</b></div><div><Network/><span>Threat Coverage</span><b>{manifest?Object.keys(manifest.categories||{}).length:'—'} TYPES</b></div><div><Braces/><span>Policy Candidate</span><b>{manifest?.policy_ground_truth_count||'—'} RULES</b></div><div><ShieldCheck/><span>Frozen Test</span><b>{manifest?.splits?.test||'—'} CASES</b></div></div>
  <div className="metrics-grid six"><MetricCard label="受保护 Agent" value={ov?.agents??'—'} sub="Active Agents" tone="mint" icon={<ShieldCheck size={16}/>}/><MetricCard label="活动契约" value={ov?.policies??'—'} sub="Active Policies" icon={<Braces size={16}/>}/><MetricCard label="运行时动作" value={ov?.actions??'—'} sub="Recorded Tool Calls" icon={<Activity size={16}/>}/><MetricCard label="阻断动作" value={ov?.blocked??'—'} sub="Hard Deny" tone="danger" icon={<ShieldAlert size={16}/>}/><MetricCard label="安全恢复" value={ov?.recovered??'—'} sub="Recovery Proposals" tone="amber" icon={<RotateCcw size={16}/>}/><MetricCard label="开放风险" value={ov?.active_risks??'—'} sub="Needs Review" tone="danger" icon={<ScanSearch size={16}/>}/></div>
  <div className="overview-grid"><section className="panel decision-panel"><SectionTitle eyebrow="RUNTIME DECISIONS" title="安全判定分布" desc="所有动作在进入 Tool 前统一经过四态决策。"/><div className="decision-wheel"><div className="wheel" style={{'--allow':`${total?((ov?.decisions?.ALLOW||0)/total)*100:25}%`,'--ask':`${total?((ov?.decisions?.ASK||0)/total)*100:25}%`,'--repair':`${total?((ov?.decisions?.REPAIR||0)/total)*100:25}%`} as React.CSSProperties}><div><b>{total||0}</b><span>Decisions</span></div></div><div className="decision-legend">{['ALLOW','ASK','REPAIR','DENY'].map(x=><div key={x}><DecisionBadge value={x}/><strong>{ov?.decisions?.[x]||0}</strong><span>{total?Math.round(((ov?.decisions?.[x]||0)/total)*100):0}%</span></div>)}</div></div></section>
   <section className="panel architecture-panel"><SectionTitle eyebrow="VERIFIABLE CONTROL LOOP" title="V3 核心技术闭环"/><div className="arch-flow"><div><Braces/><small>01 · COMPILE</small><b>P2C-V</b><span>Policy → Graph IR</span></div><ArrowRight/><div><Cpu/><small>02 · PROVE</small><b>Formal Verify</b><span>Model Check + CEGAR</span></div><ArrowRight/><div className="accent"><ShieldCheck/><small>03 · ENFORCE</small><b>Runtime Guard</b><span>ALLOW / ASK / REPAIR / DENY</span></div><ArrowRight/><div><Database/><small>04 · EVIDENCE</small><b>Audit Chain</b><span>Traceable Result</span></div></div><div className="latency-row"><Timer size={15}/><span>进程内决策耗时（当前测量）</span><b>{metrics?.runtime_overhead_ms??'—'} ms</b></div></section></div>
  <div className="two-col wide-left"><section className="panel"><SectionTitle eyebrow="ABLATION SNAPSHOT" title="为什么完整轨迹不是装饰" desc="冻结测试集比较无防护、单步防护和完整轨迹防护。"/><div className="compare-bars">{compare.map((x:any)=><div className="compare-line" key={x.name}><div><b>{x.name}</b><span>ASR {(x.asr*100).toFixed(0)}% · Fidelity {(x.policy_fidelity*100).toFixed(0)}%</span></div><div className="dual-track"><i style={{width:`${x.asr*100}%`}}/><em style={{width:`${x.policy_fidelity*100}%`}}/></div></div>)}</div><div className="chart-key"><span><i className="key-risk"/>Attack Success Rate ↓</span><span><i className="key-safe"/>Policy Fidelity ↑</span></div></section>
   <section className="panel"><SectionTitle eyebrow="ACTIVE RISKS" title="当前风险"/>{risks.length?<div className="risk-feed">{risks.slice(0,5).map(r=><div key={r.id}><RiskBadge value={r.severity}/><div><b>{r.type}</b><small>{r.description}</small></div></div>)}</div>:<Empty text="当前没有开放风险"/>}</section></div>
  <section className="panel timeline-panel"><SectionTitle eyebrow="EVIDENCE STREAM" title="最近安全证据" desc="策略编译、Formal Verify、Gateway 判定和 Tool Result 都进入可追踪证据链。"/><div className="timeline-v2">{timeline.length?timeline.slice(0,8).map((e:any,i)=><div key={e.event_id}><span className="timeline-index">{String(i+1).padStart(2,'0')}</span><i/><div><b>{e.event_type}</b><small>{e.payload?.reason||e.payload?.policy_id||e.payload?.action_id||e.trace_id}</small></div><code>{String(e.hash||'').slice(0,12)}…</code><time>{String(e.created_at||'').replace('T',' ').slice(5,19)}</time></div>):<Empty text="运行一次策略编译或 Runtime Demo 后生成证据"/>}</div></section>
 </PageShell>
}
