import React,{useEffect,useState} from 'react';
import {api} from '../api/client';
import {PageShell,SectionTitle} from '../components/Chrome';
import {CheckCircle2,Braces,Play,Save,ShieldCheck,RefreshCw,FileText,Network,SearchCode,TriangleAlert,Sparkles,ArrowRight,Cpu,GitMerge,ScanSearch,Code2} from 'lucide-react';
const samples=[
 {name:'敏感数据外发控制',text:'未经主管授权，任何 Agent 不得向外部服务发送客户联系方式或敏感数据。'},
 {name:'退款时序约束',text:'退款前必须先完成身份认证和订单确认。'},
 {name:'高金额审批',text:'金额 >= 2000 的操作需要主管审批。'}
];
export default function PolicyStudio(){
 const [idx,setIdx]=useState(0),[text,setText]=useState(samples[0].text),[name,setName]=useState(samples[0].name),[result,setResult]=useState<any>(null),[loading,setLoading]=useState(false),[policies,setPolicies]=useState<any[]>([]),[active,setActive]=useState(false),[providers,setProviders]=useState<any>(null),[provider,setProvider]=useState('deterministic'),[showSmt,setShowSmt]=useState(false);
 const load=async()=>setPolicies(await api.get('/api/v1/policies'));
 useEffect(()=>{load();api.get('/api/v1/compiler/providers').then((x:any)=>{setProviders(x);const llm=x.providers?.find((p:any)=>p.id==='openai-compatible'&&p.available);if(llm&&x.default!=='deterministic')setProvider('openai-compatible')})},[]);
 async function compile(){setLoading(true);setActive(false);try{const p=await api.post('/api/v1/policies',{name,natural_text:text,tags:'p2cv-v3,formal,policy-studio'});const r=await api.post(`/api/v1/policies/${p.id}/compile`,{provider});setResult({...r,policy_id:p.id});await load()}finally{setLoading(false)}}
 async function activate(){if(!result)return;await api.post(`/api/v1/policies/${result.policy_id}/activate`,{});setActive(true);await load()}
 function sample(){const n=(idx+1)%samples.length;setIdx(n);setName(samples[n].name);setText(samples[n].text);setResult(null);setActive(false);setShowSmt(false)}
 const verification=result?.verification||{};const formal=result?.formal_verification||{};const model=formal?.model_check||{};
 const stages=['EXTRACT','GRAPH IR','CONTRACT','FORMAL IR','MODEL CHECK','CEGAR','VERIFY'];
 return <PageShell title="策略工作台">
  <SectionTitle eyebrow="P2C-V V3 / VERIFIABLE POLICY COMPILATION" title="从自然语言制度，到可检查的 Agent 行为契约" desc="V3 将结构化抽取、Typed Graph IR、Formal IR、有界模型检查和反例驱动修复放进同一条可追踪编译链。" action={<div className="toolbar"><select className="provider-select" value={provider} onChange={e=>setProvider(e.target.value)}><option value="deterministic">Deterministic · Offline</option><option value="openai-compatible" disabled={!providers?.providers?.find((p:any)=>p.id==='openai-compatible')?.available}>LLM · OpenAI-compatible</option></select><button className="btn ghost" onClick={sample}><RefreshCw size={15}/>切换示例</button><button className="btn primary" onClick={compile} disabled={loading}><Play size={15}/>{loading?'正在验证…':'运行 P2C-V V3'}</button></div>}/>
  <div className="compiler-status v3">{stages.map((s,i)=><React.Fragment key={s}><div className={result?'done':loading&&i===0?'running':''}><span>{i+1}</span><b>{s}</b></div>{i<stages.length-1&&<i/>}</React.Fragment>)}</div>
  <div className="policy-v2-grid"><section className="panel policy-editor"><div className="panel-head"><span><FileText size={16}/>Natural Policy</span><span className="chip">SOURCE</span></div><label>策略名称<input value={name} onChange={e=>setName(e.target.value)}/></label><label>自然语言正文<textarea value={text} onChange={e=>setText(e.target.value)} rows={10}/></label><div className="editor-hint"><Sparkles size={16}/><div><b>Requirement Schema V3</b><span>Subject · Action · Resource · Destination · Condition · Temporal · Approval · Exception · Evidence</span></div></div></section>
   <section className="panel structured-panel"><div className="panel-head"><span><SearchCode size={16}/>Structured Requirement</span><span className={'chip '+(result?'ok':'')}>{result?result.extraction?.provider?.toUpperCase():'WAITING'}</span></div>{result?<><div className="structured-list">{[['ACTION',result.structured.action],['RESOURCE',result.structured.resource],['DESTINATION',result.structured.destination],['EFFECT',result.structured.effect],['TEMPORAL',(result.structured.temporal_constraints||[]).join(' → ')||'—'],['EXCEPTION',result.structured.exception||'—']].map(([a,b])=><div key={a}><small>{a}</small><b>{b}</b></div>)}</div><div className="extract-foot"><Cpu size={14}/><span>{result.extraction?.model}</span>{result.extraction?.fallback_used&&<b>FALLBACK</b>}</div></>:<div className="compile-empty"><SearchCode/><b>等待语义抽取</b><span>Extractor 结果是 Graph IR 和 Formal IR 的唯一上游输入。</span></div>}</section>
   <section className="panel contract-panel"><div className="panel-head"><span><Braces size={16}/>Executable Contract</span>{result&&<span className={'chip '+(result.verified?'ok':'warn')}>{result.verified?<><CheckCircle2 size={12}/>模型检查通过</>:<><TriangleAlert size={12}/>REVIEW</>}</span>}</div>{result?<><pre>{result.dsl}</pre><button className={'btn '+(active?'success':'primary')+' full'} onClick={activate} disabled={active||!result.formal_verification?.verified}><Save size={15}/>{active?'已激活到 Runtime':result.formal_verification?.verified?'激活当前 Contract':'Formal Check 未通过'}</button></>:<div className="compile-empty"><Braces/><b>等待 Contract</b><span>形式检查仅覆盖建模范围，自然语言含义仍需人工核对。</span></div>}</section>
  </div>
  <div className="two-col wide-left"><section className="panel"><SectionTitle eyebrow="TYPED REQUIREMENT GRAPH" title="规则中间表示 Graph IR" desc="Graph IR 连接自然语言证据与执行约束，每个节点保留来源片段，便于消融和解释。"/>{result?<div className="req-graph-v2">{result.graph.nodes.map((n:any,i:number)=><React.Fragment key={n.id}><div className={'rg-node n-'+String(n.type).toLowerCase()}><small>{n.type}</small><b>{n.label}</b></div>{i<result.graph.nodes.length-1&&<ArrowRight size={15}/>}</React.Fragment>)}</div>:<div className="compile-empty compact"><Network/><span>运行编译后显示 Typed Requirement Graph</span></div>}</section>
   <section className="panel formal-card"><SectionTitle eyebrow="FORMAL VERIFICATION" title="模型检查与证明证据"/>{result?<><div className="formal-hero"><div className={formal.verified?'proof-seal ok':'proof-seal warn'}><ShieldCheck size={24}/><b>{formal.verified?'BOUNDED':'REVIEW'}</b></div><div><small>MODEL CHECK BACKEND</small><strong>{model.backend||'—'}</strong><span>{model.state_space||0} states explored · {model.counterexample_count||0} violations</span></div></div><div className="proof-grid"><div><ScanSearch size={14}/><span>Semantic</span><b>{Math.round((verification.semantic_confidence||0)*100)}%</b></div><div><Network size={14}/><span>Coverage</span><b>{Math.round((verification.constraint_coverage||0)*100)}%</b></div><div><GitMerge size={14}/><span>CEGAR Rounds</span><b>{result.cegar?.rounds||0}</b></div><div><Cpu size={14}/><span>Z3 Adapter</span><b>{formal.solver?.status||'OPTIONAL'}</b></div></div><button className="btn ghost full" onClick={()=>setShowSmt(v=>!v)}><Code2 size={14}/>{showSmt?'收起 SMT-LIB2':'查看 SMT-LIB2'}</button>{showSmt&&<pre className="smt-code">{result.smt2}</pre>}</>:<div className="compile-empty compact"><ShieldCheck/><span>模型检查状态空间、反例与 SMT-LIB2 会显示在这里</span></div>}</section></div>
  {result&&<section className="panel proof-strip"><div><small>ADVERSARIAL WITNESSES</small><strong>{result.counterexamples?.length||0}</strong><span>Boundary / Temporal test cases</span></div><div><small>FORMAL COUNTEREXAMPLES</small><strong>{model.counterexample_count||0}</strong><span>Violation means contract semantics are inconsistent</span></div><div><small>HUMAN REVIEW</small><strong>{verification.human_review_required?'REQUIRED':'NOT REQUIRED'}</strong><span>{result.structured.ambiguity_flags?.join(' · ')||'No unresolved ambiguity'}</span></div><div><small>PIPELINE STATUS</small><strong>{result.status}</strong><span>{result.pipeline?.length||0} traceable stages</span></div></section>}
  <section className="panel registry-v2"><SectionTitle eyebrow="POLICY REGISTRY" title="策略注册表"/><div className="policy-list-v2">{policies.slice(0,8).map(p=><div key={p.id}><span className={'state-dot '+p.status}/><div><b>{p.name}</b><small>{p.id} · v{p.version}</small><p>{p.natural_text}</p></div><span className={'chip '+(p.status==='active'?'ok':'')}>{p.status.toUpperCase()}</span></div>)}</div></section>
 </PageShell>
}
