import React,{useEffect,useState} from 'react';
import {api} from '../api/client';
import {PageShell,SectionTitle} from '../components/Chrome';
import {Route,Database,UserRound,Bot,Wrench,Cloud,ArrowRight,Layers3,RefreshCw,ShieldCheck,GitCommit,FileKey2} from 'lucide-react';
const typeIcon:any={User:UserRound,Agent:Bot,Data:Database,Tool:Wrench,Destination:Cloud,Action:GitCommit,Decision:ShieldCheck,Policy:FileKey2};
const types=['User','Agent','Action','Data','Tool','Destination','Decision','Policy'];
export default function Provenance(){
 const [traces,setTraces]=useState<any[]>([]),[trace,setTrace]=useState(''),[graph,setGraph]=useState<any>(null),[ctx,setCtx]=useState<any>(null);
 async function loadTraces(){const x=await api.get('/api/v1/trajectories');setTraces(x);if(!trace&&x[0])setTrace(x[0].id)}
 useEffect(()=>{loadTraces()},[]);useEffect(()=>{if(!trace)return;Promise.all([api.get(`/api/v1/trajectories/${trace}/provenance`),api.get(`/api/v1/trajectories/${trace}/context`)]).then(([g,c])=>{setGraph(g);setCtx(c)})},[trace]);
 const groups:any={};types.forEach(t=>groups[t]=[]);graph?.nodes?.forEach((n:any)=>(groups[n.type]||groups.Data).push(n));
 return <PageShell title="溯源图谱">
  <SectionTitle eyebrow="AGENT PROVENANCE GRAPH / INFORMATION FLOW" title="把一条 Agent 轨迹重建成可解释的数据流证据" desc="V3 图谱统一 Action、Decision、Policy 节点，让“谁做了什么、为什么被判定、数据流向哪里”落到同一张图上。" action={<div className="toolbar"><select className="trace-select" value={trace} onChange={e=>setTrace(e.target.value)}><option value="">选择 Trace</option>{traces.map(t=><option value={t.id} key={t.id}>{t.id} · {t.agent_id}</option>)}</select><button className="btn ghost" onClick={loadTraces}><RefreshCw size={14}/>刷新</button></div>}/>
  <section className="panel provenance-panel-v2"><div className="graph-toolbar"><div><span className="pulse-dot"/><b>{trace||'NO TRACE SELECTED'}</b><small>{graph?.stats?.nodes||0} nodes · {graph?.stats?.edges||0} edges</small></div><span className={'chip '+(graph?.risk_paths?.length?'warn':'ok')}>{graph?.risk_paths?.length?`${graph.risk_paths.length} RISK PATH`:'NO LEAK PATH'}</span></div>{graph?.nodes?.length?<div className="prov-grid-v2">{types.filter(t=>groups[t]?.length).map((type,gi)=>{const I=typeIcon[type]||Layers3;return <React.Fragment key={type}><div className={'prov-column c-'+type.toLowerCase()}><div className="lane-title"><I size={14}/><span>{type}</span><b>{groups[type].length}</b></div>{groups[type].map((n:any)=><div className="prov-node-v2" key={n.id}><I size={16}/><div><b>{n.label}</b><small>{n.id}</small></div>{n.meta?.sensitive&&<span className="sensitive-dot"/>}</div>)}</div>{gi<types.filter(t=>groups[t]?.length).length-1&&<div className="prov-arrow"><ArrowRight size={16}/></div>}</React.Fragment>})}</div>:<div className="graph-empty"><Route size={42}/><h3>暂无真实运行轨迹</h3><p>到“实时运行”执行 MCP Call 后，这里会自动构建 Provenance Graph。</p></div>}
  </section>
  <div className="two-col wide-left"><section className="panel"><SectionTitle eyebrow="EDGE EVIDENCE" title="关系证据"/><div className="edge-list">{graph?.edges?.length?graph.edges.slice(0,14).map((e:any,i:number)=><div key={i}><code>{e.source}</code><span>{e.type}</span><ArrowRight size={13}/><code>{e.target}</code></div>):<p className="muted">暂无边关系。</p>}</div></section><section className="panel"><SectionTitle eyebrow="TRAJECTORY CONTEXT" title="上下文重建"/><div className={'sensitivity-card '+(ctx?.sensitive_context?'warning':'safe')}><Database size={22}/><div><small>SENSITIVE CONTEXT</small><strong>{ctx?.sensitive_context?'DETECTED':'CLEAN'}</strong><p>{ctx?.sensitive_context?'历史轨迹携带敏感上下文，外发行为会被升级检查。':'当前没有发现敏感历史状态。'}</p></div></div><div className="contract-count"><Layers3 size={18}/><span>活动行为契约</span><b>{ctx?.active_contracts||0}</b></div></section></div>
 </PageShell>
}
